name: Check coverage for PR

on:
  pull_request:

jobs:
  run-tests-check-coverage:
    runs-on: ubuntu-20.04
    name: Run tests & check coverage
    permissions:
      checks: write
      pull-requests: write
      contents: read # for private repos
    steps:
      - uses: actions/checkout@v3
      - name: Jest coverage comment
        id: coverage
        uses: ArtiomTr/jest-coverage-report-action@f1a1382101d9b92b38e3df05c9ed89a834af97c8
        with:
          package-manager: yarn
          output: report-markdown
      - run: yarn test:coverage
      - name: Read coverage text report
        uses: fingerprintjs/action-coverage-report-md@v1
        id: coverage-md
      - uses: marocchino/sticky-pull-request-comment@adca94abcaf73c10466a71cc83ae561fd66d1a56
        with:
          message: |
            ${{ steps.coverage.outputs.report }}
            <details>
              <summary>Show full coverage report</summary>

              ${{ steps.coverage-md.outputs.markdownReport }}
            </details>
